const {onSchedule}=require('firebase-functions/v2/scheduler');
const {onRequest}=require('firebase-functions/v2/https');
const {defineSecret}=require('firebase-functions/params');
const admin=require('firebase-admin');
const crypto=require('crypto');
const express=require('express');
admin.initializeApp();
const db=admin.firestore();
const WABA_TOKEN=defineSecret('WABA_TOKEN');
const WABA_PHONE_ID=defineSecret('WABA_PHONE_ID');
const WABA_TEMPLATE=defineSecret('WABA_TEMPLATE');
const RZP_ID=defineSecret('RAZORPAY_KEY_ID');
const RZP_SECRET=defineSecret('RAZORPAY_KEY_SECRET');
const RZP_WEBHOOK=defineSecret('RAZORPAY_WEBHOOK_SECRET');
function balance(i){return Math.max(0,Number(i.amount||0)-Number(i.paidAmount||0))}
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})}
function cleanPhone(p){return String(p||'').replace(/\D/g,'')}
async function authUid(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw new Error('Missing bearer token');return (await admin.auth().verifyIdToken(h.slice(7))).uid}
async function wabaSend(phone,text){const token=WABA_TOKEN.value(),id=WABA_PHONE_ID.value(),template=WABA_TEMPLATE.value();if(!token||!id||!template)return {sent:false,reason:'WhatsApp secrets/template not configured'};const r=await fetch(`https://graph.facebook.com/v23.0/${id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:cleanPhone(phone),type:'template',template:{name:template,language:{code:'en'},components:[{type:'body',parameters:[{type:'text',text}]}]}})});const data=await r.json();if(!r.ok)throw new Error(JSON.stringify(data));return {sent:true,data}}
exports.dailyDueEngine=onSchedule({schedule:'every day 09:15',timeZone:'Asia/Kolkata',secrets:[WABA_TOKEN,WABA_PHONE_ID,WABA_TEMPLATE]},async()=>{const bs=await db.collection('businesses').get();const t=today();for(const b of bs.docs){const invs=await b.ref.collection('invoices').where('reminderEnabled','==',true).get();for(const d of invs.docs){const i=d.data();const bal=balance(i);if(!i.dueDate||bal<=0||i.status==='PAID')continue;const due=new Date(`${i.dueDate}T00:00:00+05:30`);const cur=new Date(`${t}T00:00:00+05:30`);const days=Math.floor((cur-due)/86400000);if(![0,2,7,15].includes(days))continue;const key=`${d.id}_${days}_${t}`;const rr=b.ref.collection('reminders').doc(key);if((await rr.get()).exists)continue;let c=null;if(i.customerId){const cs=await b.ref.collection('customers').doc(i.customerId).get();if(cs.exists)c=cs.data()}const message=`Hello ${c?.name||'Customer'}, this is a payment reminder for invoice ${i.invoiceNumber||d.id}. Outstanding balance: ₹${bal.toFixed(2)}. If already paid, please ignore or share the reference.`;const rec={invoiceId:d.id,customerId:i.customerId||null,daysOverdue:Math.max(days,0),channel:'WHATSAPP',status:'QUEUED',message,createdAt:admin.firestore.FieldValue.serverTimestamp()};if(c?.phone){try{const r=await wabaSend(c.phone,message);rec.status=r.sent?'SENT':'QUEUED';if(!r.sent)rec.reason=r.reason}catch(e){rec.status='FAILED';rec.error=String(e.message).slice(0,500)}}await rr.set(rec)}}});
exports.createRazorpayPaymentLink=onRequest({secrets:[RZP_ID,RZP_SECRET]},async(req,res)=>{res.set('Access-Control-Allow-Origin','*');if(req.method==='OPTIONS')return res.status(204).send('');try{const uid=await authUid(req);const {invoiceId}=req.body||{};if(!invoiceId)return res.status(400).json({error:'invoiceId required'});const ref=db.doc(`businesses/${uid}/invoices/${invoiceId}`),s=await ref.get();if(!s.exists)return res.status(404).json({error:'Invoice not found'});const i=s.data(),amt=Math.round(balance(i)*100);if(amt<=0)return res.status(400).json({error:'Invoice already paid'});const basic=Buffer.from(`${RZP_ID.value()}:${RZP_SECRET.value()}`).toString('base64');const r=await fetch('https://api.razorpay.com/v1/payment_links',{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/json'},body:JSON.stringify({amount:amt,currency:'INR',description:`DUEFORCE ${i.invoiceNumber||invoiceId}`,notes:{invoiceId,businessId:uid}})});const data=await r.json();if(!r.ok)return res.status(r.status).json(data);await ref.update({paymentLink:data.short_url,paymentLinkId:data.id,updatedAt:admin.firestore.FieldValue.serverTimestamp()});res.json({url:data.short_url,id:data.id})}catch(e){res.status(401).json({error:e.message})}});
const app=express();app.use(express.raw({type:'application/json'}));app.post('/',async(req,res)=>{try{const sig=req.headers['x-razorpay-signature'];const expected=crypto.createHmac('sha256',RZP_WEBHOOK.value()).update(req.body).digest('hex');if(!sig||sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return res.status(400).send('invalid signature');const event=JSON.parse(req.body.toString());const eventId=event.id||crypto.createHash('sha256').update(req.body).digest('hex');const er=db.doc(`webhookEvents/${eventId}`);if((await er.get()).exists)return res.status(200).send('duplicate');await er.set({event:event.event,createdAt:admin.firestore.FieldValue.serverTimestamp()});const entity=event.payload?.payment?.entity||event.payload?.payment_link?.entity;const uid=entity?.notes?.businessId,id=entity?.notes?.invoiceId;if(uid&&id&&(event.event==='payment.captured'||event.event==='payment_link.paid')){const ref=db.doc(`businesses/${uid}/invoices/${id}`),s=await ref.get();if(s.exists){const i=s.data(),add=Number(entity.amount||0)/100,paid=Math.min(Number(i.amount||0),Number(i.paidAmount||0)+add),status=paid>=Number(i.amount||0)?'PAID':'PARTIAL';await ref.update({paidAmount:paid,status,reminderEnabled:status!=='PAID',updatedAt:admin.firestore.FieldValue.serverTimestamp()});await db.collection(`businesses/${uid}/payments`).doc(eventId).set({invoiceId:id,invoiceNumber:i.invoiceNumber||id,amount:add,method:'Razorpay',provider:'razorpay',reference:entity.id||eventId,createdAt:admin.firestore.FieldValue.serverTimestamp()})}}res.send('ok')}catch(e){console.error(e);res.status(500).send('error')}});exports.razorpayWebhook=onRequest({secrets:[RZP_WEBHOOK]},app);
